### ISSUE TITLE
czmod is not faster than zoxide

### ISSUE THREAD

**Issue by ajeetdsouza** [skywind3000/czmod#1]
Please remove this information from your README, as it is incorrect.

You have done your benchmarking with an _empty_ database. However, this does not reflect a real world use case, where the average user would be expected to have around 500 entries in his/her database. I've written a script to populate both `zoxide` and `z.lua` databases, and it can be seen that **`zoxide` runs 5x faster than `czmod`.**

Here is the script:

```bash
#!/usr/bin/env bash
rm ~/.zo ~/.zo.tmp ~/.zlua
for i in {1..500}; do
        dirname="/tmp/test$i"
        mkdir -p "$dirname"
        ~/git/zoxide/target/x86_64-unknown-linux-musl/release/zoxide add "$dirname"
        ~/git/czmod/czmod --add "$dirname"
done
```

Now if I run `hyperfine` on my machine:

```bash
$ hyperfine '~/ws/zoxide/target/x86_64-unknown-linux-musl/release/zoxide 
query test' '~/git/czmod/czmod -e test' --warmup 5000 --min-runs 5000
```

This is what I get:

```
Benchmark #1: ~/ws/zoxide/target/x86_64-unknown-linux-musl/release/zoxide query test
  Time (mean ± σ):       0.4 ms ±   0.4 ms    [User: 0.6 ms, System: 0.3 ms]
  Range (min … max):     0.0 ms …   5.2 ms    5000 runs
 
  Warning: Command took less than 5 ms to complete. Results might be inaccurate.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
 
Benchmark #2: ~/git/czmod/czmod -e test
  Time (mean ± σ):       2.2 ms ±   0.4 ms    [User: 2.3 ms, System: 0.2 ms]
  Range (min … max):     1.8 ms …   7.0 ms    5000 runs
 
  Warning: Command took less than 5 ms to complete. Results might be inaccurate.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
 
Summary
  '~/ws/zoxide/target/x86_64-unknown-linux-musl/release/zoxide query test' ran
    5.01 ± 5.08 times faster than '~/git/czmod/czmod -e test'
```

I tried to benchmark DB additions, but we have to first set `_ZO_MAXAGE` and `_ZL_MAXAGE` to a large number to ensure that all the other entries don't get deleted. However, `czmod` doesn't seem to follow `_ZL_MAXAGE`, so I was unable to test this.

I would have liked to test this on another machine, but unfortunately, I only have access to one at the moment. @cole-h, would you be able to do this?

**Comment by cole-h** [comment]
I think these kinds of pissing contests are unproductive and give open source a bad name. I think it is incredibly rude to invade a competing project's issue tracker and call them out, despite what they might or might not have done to you in the past.

I also think it is extremely hypocritical that you removed/locked/otherwise censored @skywind3000's (albeit also rude) topic(s) decrying the differences in performance, yet here you are doing the same thing.

I understand that this libel about performance may frustrate you. Competition is good. It drives all involved parties to better their software in order to attract more users. As with all software, it's about trade-offs. Some people don't want to have Rust on their system. Some people hate compiling and debugging C projects. Some people want the raw performance that both Rust and C can offer. Some people want the least amount of dependencies possible in their software.

I participated in the first topic on `zoxide` for the same reason I will not participate here: it is incredibly rude to visit your competition's issue tracker and attack them and their claims to performance (no matter whether or not you are in the right).

Instead of filing these combative issues that just spread toxicity and "I-was-right-haha" behavior, why not focus on your respective projects? One of open source's greatest strengths is that, if you dislike the way a specific project is being run, you can either fork it or create an alternative project that fulfills all your needs. That's what skywind did here: they were satisfied with their Lua implementation, but upon seeing `zoxide`, got inspired and found a way to complement the original project and make it faster.

I hope we can stop this cycle of viciousness here. If performance really matters to someone, I want to believe that they will act in good faith and experiment with both projects, utilizing whichever fulfills their needs and desires more.

I'll stop here. I don't plan on responding to this issue further. Let's stay positive and spread the love.

**Comment by ajeetdsouza** [comment]
@cole-h, I did think twice before creating this issue for the same reason. 

However, I also did remove all comparisons from the `zoxide` README once I realized that they were inspiring toxicity and not in the spirit of open source. 

I tagged you in this because I needed a second opinion, due to the fact that the performance of the musl target seemed to vary a lot across machines, as @skywind3000 had pointed out.

Perhaps I should have done this over mail instead? @skywind3000, feel free to delete this issue, but do consider removing the benchmarks from your README.

**Comment by skywind3000** [comment]
Because I created czmod in one day, without any optimizing. For example, czmod will sort the database everytime with an O(N^2) algorithm.

I've been busy recently, and I can polish czmod a little at the weekend.

btw, comparison in README will be removed after that.

**Comment by ajeetdsouza** [comment]
I think the slowdown might be more due to the fact that you're using a plaintext DB; however, I would be very interested to see your findings. Do let me know, and I'm glad we could come to an agreement!
